doctrine_migrations:
    storage:
        table_storage:
            table_name: '%app.name%_migrations'
            version_column_name: 'version'
            version_column_length: 1024
            executed_at_column_name: 'executed_at'
            execution_time_column_name: 'execution_time'
    migrations_paths:
        'DoctrineMigrations': '%kernel.project_dir%/migrations'
    organize_migrations: "BY_YEAR_AND_MONTH"
    custom_template: ~
    all_or_nothing: false
    check_database_platform: true
