framework:
    notifier:
        chatter_transports:
            telegram: '%env(TELEGRAM_DSN)%'
        channel_policy:
            urgent: [ 'chat/telegram' ]
            high: [ 'chat/telegram' ]
            medium: [ 'chat/telegram' ]
            low: [ 'chat/telegram' ]
        admin_recipients:
            - { email: contact@devscast.tech }
