twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        app_name: '%app.name%'
        app_locales: '%app.locales%'
    form_themes: [ 'bootstrap_4_layout.html.twig' ]
    date:
        format: d F Y
        interval_format: '%%d days'
    paths:
        '%kernel.project_dir%/templates/dashboard': dashboard
