app_index:
    path: /
    controller: App\Controller\Webhook\GithubWebhookController::main

app_webhook_github:
    path: /webhook/github
    controller: App\Controller\Webhook\GithubWebhookController::index
    methods: [POST]

app_webhook_telegram:
    path: /webhook/telegram
    controller: App\Controller\Webhook\TelegramWebhookController::index
    methods: [POST]
